function go(n){S.step=n;S.err="";render();scrollTo({top:0})}
function prog(){return `<div class="prog">${["CV","Vaga","Análise","Candidatura","Entrevista"].map((t,i)=>`<div class="${S.step==i+1?"on":S.step>i+1?"done":""}">${i+1} ${t}</div>`).join("")}</div>`}
function render(){const a=$("#app");let h="";
if(S.step==0)h=`<section class="hero"><div class="eyebrow">AI JOB APPLICATION COPILOT</div><h1>O teu CV está preparado para esta vaga?</h1><p>Analisa o teu CV, compara-o com uma vaga e prepara uma candidatura mais forte com assistência de IA.</p><div class="row"><button class="btn t" onclick="track('start_application');go(1)">Analisar o meu CV</button><a class="btn alt" href="#como">Como funciona?</a><button class="btn alt" onclick="loadDemo()">Ver demo</button></div></section>
<section id="como" class="steps3">${[["01","Envia o teu CV"],["02","Cola a descrição da vaga"],["03","Recebe uma análise e prepara a tua candidatura"]].map(([n,t])=>`<div class="card"><div class="n">${n}</div>${t}</div>`).join("")}</section>
<div class="mock"><div class="ring" style="--p:78"><i>78</i></div><div><b>Compatibilidade com a vaga</b> <span class="demo">EXEMPLO</span><br><span class="note">Pré-visualização ilustrativa, não são dados reais.</span></div></div>
<div class="card"><h3>Grátis vs Premium</h3><p><b>Grátis:</b> pontuação, pontos fortes e lacunas básicas.<br><b>Premium (${CONFIG.PRICE}):</b> análise completa, carta, email e preparação de entrevista.</p></div>`;
else if(S.step==1)h=prog()+`<h2>O teu CV</h2><div class="card"><label class="drop" for="f">Arrasta o teu CV aqui ou selecciona um ficheiro.<br><span class="note">PDF ou DOCX, até 5 MB</span><input id="f" type="file" accept=".pdf,.docx" class="hide" onchange="onFile(this.files[0])"></label><p>Ou cola o conteúdo do teu CV abaixo.</p><textarea id="cv" oninput="S.cv=this.value;cnt('cv','c1')">${esc(S.cv)}</textarea><div class="cnt" id="c1">${S.cv.length} caracteres</div></div><div class="err ${S.err?"":"hide"}">${esc(S.err)}</div><button class="btn" onclick="next1()">Continuar</button>`;
else if(S.step==2)h=prog()+`<h2>A vaga</h2><div class="card"><textarea id="vac" placeholder="Cola aqui a descrição completa da vaga, incluindo requisitos e responsabilidades." oninput="S.vac=this.value;cnt('vac','c2')">${esc(S.vac)}</textarea><div class="cnt" id="c2">${S.vac.length} caracteres</div></div><div class="err ${S.err?"":"hide"}">${esc(S.err)}</div><div class="row"><button class="btn alt" onclick="go(1)">Voltar</button><button class="btn" onclick="next2()">Analisar</button></div>`;
else if(S.step==3)h=prog()+(S.busy?`<div class="card"><h3>A analisar…</h3><div class="sk"></div><div class="sk" style="width:70%"></div><div class="sk" style="width:85%"></div></div>`:S.err?`<div class="err">${esc(S.err)}</div><button class="btn" onclick="runAnalysis()">Tentar novamente</button>`:analysis());
else if(S.step==4)h=prog()+kitView();else h=prog()+ivView();
a.innerHTML=h}
function cnt(i,o){$("#"+o).textContent=$("#"+i).value.length+" caracteres"}
function loadDemo(){Object.assign(S,{demo:true,cv:DEMO.cv,vac:DEMO.vac,res:DEMO.res,kit:DEMO.kit,iv:DEMO.iv});go(3)}
const list=(a,e)=>(a||[]).length?`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:`<p class="note">Nada a assinalar.</p>`;
function analysis(){const r=S.res;if(!r)return"";const sc=Math.max(0,Math.min(100,+r.score||0)),cats={essential:"Requisitos essenciais",preferred:"Preferenciais",responsibility:"Responsabilidades",technical:"Competências técnicas",soft:"Competências pessoais",education:"Formação",experience:"Experiência",language:"Línguas"},lab={MATCH:"Correspondência",PARTIAL:"Parcial",NOT_FOUND:"Não identificado no CV."};
return`${S.demo?'<span class="demo">DEMO</span>':""}<div class="card score"><div class="ring" style="--p:${sc}"><i>${sc}/100</i></div><div><h3>Compatibilidade com a vaga</h3><p class="note">Esta pontuação é uma estimativa baseada na correspondência entre o conteúdo do teu CV e os requisitos identificados na vaga. Não prevê o resultado da candidatura.</p></div></div>
<div class="card"><h3>🟢 Pontos fortes</h3>${list(r.strengths)}<h3>🟡 A melhorar</h3>${list(r.partial_matches)}<h3>🔴 Lacunas</h3>${list(r.missing_from_cv)}<p class="note">“Não identificado” não significa que não possuis a competência, apenas que não aparece no CV.</p></div>
<div class="card"><h3>Requisitos da vaga</h3>${Object.keys(cats).map(k=>{const it=(r.requirements||[]).filter(x=>x.category==k);return it.length?`<details><summary>${cats[k]} (${it.length})</summary>${it.map(x=>`<div class="req"><span class="tag ${x.status}">${lab[x.status]||""}</span> ${esc(x.text)}<div class="note">${esc(x.evidence)}</div></div>`).join("")}</details>`:""}).join("")}</div>
<div class="card"><h3>Melhorias ao CV</h3>${(r.recommendations||[]).slice(0,S.code||S.demo?99:1).map(x=>`<p><b>Actual:</b> “${esc(x.current)}”<br><b>Direcção:</b> ${esc(x.direction)}</p>`).join("")}<div class="warn">Revê todas as sugestões antes de as utilizar. Não incluas experiências ou competências que não possuis.</div></div>
<div class="row"><button class="btn t" onclick="go(4)">Preparar candidatura</button></div>`}
function lockBox(){return`<div class="card lock"><h3>🔒 Premium</h3><p>Desbloqueia a candidatura completa.</p><a class="btn t" href="${wa()}" target="_blank" rel="noopener" onclick="track('premium_clicked');track('whatsapp_clicked')">Desbloquear por ${CONFIG.PRICE}</a><p class="note">O pagamento é combinado por WhatsApp (não é automático). Já tens um código?</p><div class="row" style="justify-content:center"><input id="code" placeholder="Código Premium" style="padding:12px;border:1px solid var(--line);border-radius:10px;font:16px inherit"><button class="btn alt" onclick="S.code=$('#code').value.trim();S.err='';go(4)">Usar código</button></div><div class="err ${S.err?"":"hide"}">${esc(S.err)}</div></div>`}
const unlocked=()=>S.demo||S.code;
function cp(id){navigator.clipboard.writeText($("#"+id).innerText).then(()=>{const b=event.target,t=b.textContent;b.textContent="Copiado ✓";setTimeout(()=>b.textContent=t,1500)})}
function kitView(){if(!unlocked())return`<h2>Kit de candidatura</h2>${lockBox()}`;if(S.busy)return`<div class="card"><div class="sk"></div><div class="sk"></div></div>`;
if(!S.kit)return`<div class="err ${S.err?"":"hide"}">${esc(S.err)}</div><button class="btn" onclick="gen('kit','kit',4)">Gerar candidatura</button>`;const k=S.kit;
const box=(id,t,x)=>`<div class="card"><h3>${t}</h3><pre id="${id}">${esc(x)}</pre><div class="row" style="margin-top:10px"><button class="btn alt" onclick="cp('${id}')">Copiar</button>${S.demo?"":`<button class="btn alt" onclick="S.kit=null;gen('kit','kit',4)">Regenerar</button>`}</div></div>`;
return`<h2>Kit de candidatura</h2>${box("k1","Carta de apresentação",k.cover_letter)}${box("k2","Email de candidatura","Assunto: "+k.email?.subject+"\n\n"+k.email?.body)}${box("k3","Resumo profissional / LinkedIn",k.profile_summary)}<div class="warn">Revê tudo antes de enviar. Confirma que cada afirmação é verdadeira.</div><br><button class="btn" onclick="go(5)">Preparar entrevista</button>`}
function ivView(){if(!unlocked())return`<h2>Entrevista</h2>${lockBox()}`;if(S.busy)return`<div class="card"><div class="sk"></div></div>`;
if(!S.iv)return`<div class="err ${S.err?"":"hide"}">${esc(S.err)}</div><button class="btn" onclick="gen('interview','iv',5)">Gerar preparação</button>`;
return`<h2>Perguntas prováveis</h2><div class="card">${(S.iv.questions||[]).map(q=>`<details><summary>${esc(q.question)}</summary><p><b>Porquê:</b> ${esc(q.why)}</p><p><b>Estrutura:</b> ${esc(q.structure)}</p><p><b>Exemplo (com base no CV):</b> ${esc(q.example)}</p></details>`).join("")}</div><div class="card"><h3>Perguntas para fazeres ao empregador</h3>${list(S.iv.ask_employer)}</div><p class="note">A preparação aumenta a confiança, mas não garante sucesso na entrevista.</p>`}
